# Generated by Django 5.1.6 on 2025-05-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='web_service.subject', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(blank=True, max_length=100, null=True)),
                ('theme_information', models.TextField()),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='web_service.chapter', verbose_name='Глава')),
            ],
        ),
    ]
